server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_management_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 610013thW.
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
      timeout: 10s
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 多环境配置
  profiles:
    active: prod

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml

# JWT配置
jwt:
  # JWT加解密使用的密钥
  secret: f4e2e52034348f86b67cde581c0f9eb5
  # JWT的有效期(单位:秒)
  expire: 86400
  # JWT存储在请求头中的名称
  header: Authorization
  # JWT前缀
  tokenPrefix: Bearer

# Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh-CN
    swagger-model-name: 实体类列表
    enable-swagger-models: true
    enable-document-manage: true
    enable-home-custom: true
    enable-footer: false
    enable-footer-custom: true
    enable-host: false
    enable-host-text: http://localhost:${server.port}${server.servlet.context-path}
    enable-request-cache: true
    enable-search: true
    enable-debug: true
    enable-open-api: true
    enable-group: true
  production: false # 非生产环境打开增强功能
  basic:
    enable: false # 是否开启Basic认证
  documents:
    - group: default
      name: 接口说明文档
      locations: classpath:markdown/*

# 日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework.security: INFO
    com.example.student: INFO
    org.springframework: WARN
    org.mybatis: INFO

# 默认头像配置
default:
  avatar:
    url: /uploads/avatar/default/default.jpg